language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: UvwJ9FNVMcWbhlZZDIW5Eop7j99YPIDPT7N98kmDIcBL3VtU4OI85TDuBCZD+aWqxGFJz+sS7QbbAQ2r36VEOdf2u8XivyOthfQi3Z4U/pkZYNXwf86/D6HRhTroo+k4+6Cizs9Y/CwkTyBGIQwwcG75AU+cFuItrkJ5SJGdTCO/HTo/U54d36Rn5GBL8gnBtVzKgsuDr+aeSo+T5lp2JrFlpFMkxgl1QEeRdYW51Toikg9yyP95ObDiToidq+ATExqWdfvbA2okcyfd/QZIlsNyLW+GarlYz4Ws9mq6AXb80J8aP69Mzq2Qy9qA+dAWf9D7rpy4IhK6yG0mP7+uqoKKlrnk0xttLotMoQM8PLQucBfWQKMKQn4TKrqvSGEgkpDKO2I9can9GfTGxhVmZP5aTPh2PpMNzNjnluIPA0ydpjIsitZ4i1Iu/PsIvvI8WF8gwHU15LwRNS5qIN+FkhK5FQo/yYeJ3MUW8SozQ5g111gJY34ZYizkntTpxikQiCq9N/chIG8suIndlG4sdxT64nPFDa+HhquHTVVhLWkzohLCKcozQPMV5hgdqLa370Kl9gFQmBCrIu63hag7nGiIriAjcEX0K5hkhwv0BmeEUSdcN53wK6yPdXFqLvuvfSAFw1beEyU+P4AmFC9U00oCiz4MaOa8IMdAUR5FuV0=
  app: tg-personal-site
  skip_cleanup: true
