language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: cKz5EX9kVXR4dEQmfnL6s2sMzlurgOx8qQD7mcSZVpucTDXBeX9vhPaAqy/Tr3oiMZe1/qKQOHKqV/QlSUcqJkgUN1c/3vsIrbgN1sPsNJ4a/Y6r8x1V2hSvRJOiHjnhWERXxVblBGQqLwaYlaFAAj8evFYoH4n57NI0A+HJuj+pVtoBsi7Ah1A0Q0Q66rV+bs60eKuOfRjVqjWCIkOdSpHS39UpmaFE5Qk/723ILWUfGgkqDYNw0usw/JoVRmmn5lIOHRbV4WNGIBbUj8kBNX0n8bg0AVWlwZHkWqcYfZNTLaBDM007lHvGAaCPF7dYEIiPQKIdz1rbRhlZslYhl72y3cz7ZnQY10hPDkQq7WWpfgEnsi+wemnAzVVsDrBlyHmZg8DhAeY1PBXmbi/O7bEnXdLoR0sjsTChOxfDgNHp1gF3N3+PZIULYb/D4aByOeNM40sGsw2+vcnkHG1vG8h5S92BYEbo2KmERjf4Cipe6uRVVXRRsPZ2CETIaCe4ouOLsOrgUX/JJuWyUU2WqngQWuoPons9A1Rz8Fv8XRR1ztIqefhznqodZ/ULhuWBXQxqO6Npq+7l9/ihftSkZgTAycZmv6UqwC9M6+xMQqQR4FkeCKChk9K6EgSb9fZV6v4ebbYNd83IhDSJMb+1D+1XiyhJebvNx3XjdUM+Ld4=
  app: tg-personal-site
  skip_cleanup: true
