language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: cAB5k1rBjExFh3SrDI4DU3vzI+dyY5m64DBJIh24dG1rJElxqa3N+BfPOZGDeP5NCE1Mvmfy6ugfkvo47DZqZmmDt+g4VT0XMvnN7KffpDb13ssngpk1UR+8LutprRCM0FlMAyhkKbA5eXGvVFlu9+QuOTfPzWp5d0mM0siCRn+kZLqm7nToiXop0G7Zb87FDcGqjOLPKekkaRVDncCmbYyI3cHoIvM0hEgvYJ1s8iRNnRXIZkzixCGynqE2+MUPF0YK8T0rkPKRxkZCoIYgpUZyukQFq0w9JcPBkKA9SePDdpbSXF5hDYLx6g2XGGCwXTj79+P2zOuR/jMQpI1iiLtogXIjBaXIALNPj5mSq3o21UU1Gt/raL5T0OjH6vZN/5Z4WXDGo7dfrjmceraLV/L4uFA/9qPh9wxZjK+hcNJ7cYMrfUnBogLnxXJOCHkjfvlwrzhvB+xTbDIKG6WRUyFg+01Xri1/0rNu63GMZYjOpBNvQ+/sr2/9ww380U5lN0NfuCh5ozBt5c3iwAN9r9+yNCNmvoWhPsaBDapU4hkt9/Dr5lryr4t9NNMbJrpLd9AhA55wyvIIayIGnfhtKWLhgJuUSWWbA3I0Uuf1hSLBMSXC+eyJXV+BDt/8AKktGVYzEHYxrwzTs+56kwjqrcOA1mLVq43iXdZxexO0ZXc=
  app: tg-personal-site
  skip_cleanup: true
