language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: GrUb96SJS8VBqJRVOUCrI1hTI2OD5x13XNuxsDiKVK9iBM8JXAHbSCEwn4UJJUOWsODESzQI+q8tEZEsXQQjVnrAw6IQD4BCsWfTg9Whv3d/9/9ITdszWroelmmusTh8TLuLrszyxR8sWsaFGIciw1YutYpC7NA4ViqoLOBf1dDprJ1w9U3bztLHOqji3/9JCO4G5SQvplXeN1NFOp9VvwYljfs685s+w+B2yOJ9QavCHGIds5MjFIWdsp1SGvnrXLGKXt9OCHB9g/JFHI9+N1L8z+Z6A+avq6NCC1ZWSW7320+tgLjssTHZ7H/smgzdjM2t+kDG3J4DfGPFw0fdUeUxfaqWfKdOqMpM6oUTx6NxkyrIUPEacIgCNtDdHJN++J9vaehDoFGiTblfeq1c6vbvVhJSMRzeqbouUZJQHjIPY7XynoxwEOA1DUNf/r3XVA9K9UGxNuyOWiOp30yLcWbBk/w1WCxmQmczSkHGgtb68i5kNzy8h+2TioFEImPc7PnuKt1XnhIUENKgPfGd6q7j5hCMrcJlyDtKmY00hXwQwsuenH+yfDH6EosMctC4h0Qsxf+P7bIDFxpCGGkcBbmfB/cMshFAAMIbp77n2rnDeFLLvgM1FTsmwULUNyy6a1ZYTAOoWBrozZUa5C9pDxbHXQ5FXTe8vDiMM42V1jU=
  app: tg-personal-site
  skip_cleanup: true
