language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: pi0hQYf5B7GIKkaMbJk0zK1NW0232snxGJwmRS+PF/bkwF+beVh6AiEQHUx5XAc7hL75gK52XS/vLED5YLPG6tQKS4e8oOS2SfQL1vGoRvMc++5e8F2+4RuR5ZDzHkMqPqYbtdRr4QoII0lFcJkx8L0trkNoxpfL3PYdvy9JBbjKxrA5dvaWud+zDEKsbtOYMx1N+tplXVE153gAgt6Q7P2vlgs/9mVt1OLvgHozByov0YUzqDsxN5TZuHp0DmT+7ViBbOokIII33BKI+isf4gJ8rI3CV7zQzM7C2ppHT5O94iH9mL9fy5w80n+q6/ZIJbrWe/foenUq2f12pHRzFDVbIibqFjjUmoKKYhxgDpbGWro1uCv1v02hnVi1fS7P165+6NaSbLeliZ+HE0bVlmJAxnAHPk+o1ZzYkgpZ/e7DhW1guuJux9AIucx5liWgHFDPkiEcKzF9ikj/CwoGt1p/Cg91FPWsJXFOuVmJbzjSLZ4AZ6oD2OE3XXyyEbnn6QLt3Er5GHP7j2GCdb7u6vfYnYO2lol1fiRDmkZaEH22/w2IYPUkq1X7XuuyeJBbjAmaT+V34qc7xWxeCrd+mR8bmBqXzjy7fM+Zj2VYNaqCV7qx5qLH6Jtzf6ZNMwLR6L3AGCSMVv4HwAwcIJNrI0AVfMoTfp7oC6WIV2ZlGwo=
  app: tg-personal-site
  skip_cleanup: true
