language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: jkOqHB0rZJoZWP8G3OuKovWB+XPNHosH7NhLpuBCCvVMKrFca9p9PGwmVLuoF9MmOBpjzOU+VCrT1a8z74Tdj0RCwXK0WiD2eF0M/hFaOksXTc7IpafbTnhcFVtCK6lZX8X4lL1ov33OTuB8SXiv50otzzxd7BJlblZB30qEVYC8iWqFhLwuDpU4QaVMbiw013jz/VL00qNAlQLN6gv2MGLaIWZT4yHZPeKkKdfmYMORErAsUOpobVocAO5WrKWKSS/BGKTyE4PeGHrS7tmDa7GOHFlDS4/bYaGjHHGSiK7N4oM2++i1fRvhtDOmE0JxMXL5oE+F19Q2oh/+fORGOPxLUGghMy5yEMeqhaycUjMI4xFyYrWZk/KtylRPn35YqEibPcYXeMAsXYyszbpFqzMik7GgV036f70YWwiFmDk6l1nGz2WvBDBsbONBO5MIHS3EGLoo0Cs2cxQ4zIaZ3iOoBe2MfnlMv/IvMbN0V8/1Ann5LL84GiHevAceYGIinuUSHv8Pxuz4A47JhRthoi7nGVw0zxihXWLxm0a5BGT5vyLxfrCLa689neo7nivugGlGHI3Qds9O8PYtBN5abvUo4PBEqT6qa1TDzEnvEc+M4rBM1libQQqsrnjUJGp+BAXzVDejsxDtUckvfSlidRA6ILZ/3Cx2bgRpVWl56HA=
  app: tg-personal-site
  skip_cleanup: true
