language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: RFUGEBWDWXdWhqxmznrtBfHZpvOf0+Q+fdDd8HniI2bnWYAeOkSmOYDLwjdBxTM5eh//yTFg5nsmz0eCdjfh4yLPIoScs5Onw1Tyd6j4V+a3VeCr1PBfeaLyqKErHWDbWBirZEpltkz8X72yZ+6LNG9qUfafQtOKdbOKLvHsGp35ZedrWbRVKiO/hWUgt9CoKIHY1Fnal91vOsl2rTj0cxhuTJllD10hE484uGdT2YRovbuHAggG/Ma8ha8T5uRlAJDPj9IKrxhaQhrqLTrVlUXpAiax6qHNnRsjbGI5BIQBm5V1i4UezGVqj3mEMTaqosQmCxZ8jyHaWCYtuZcPpNVh1Pc5FR0wL3iBXoWYIZm09XxKrdsj/PYPHzkPQ9ohKmO4Uyo8wQZ5JPrC8wLLlT8IUxqruwlaC/fcDTRN8G1L8adMGXcVMr+qaRZHifQBjh5pd1UIhqdFY+GUUGe1NLbK9P5s3OsJl5BOptdivtdPvnB/R7AETdDyCf2GQM76LpMr5teSOgQBKxNnRjwbp0FIizYh0cSYjPwG+fa6VSgb7iOp6X8EJZ7/XEEXohKPiMkdu87Hnpq2BHbTspo8A4Cv9in3D9eyeAJZOGtmSjpoHfvchC91VL/6/uF8d/RBok5wT2TnmFIn5gC2NOrgr8SpL8OrDtqCZgy6qa87zv4=
  app: tg-personal-site
  skip_cleanup: true
